// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/payslip_summary/contract.go

// Package payslipsummary is a generated GoMock package.
package payslipsummary

import (
	context "context"
	presentations "payslips/internal/presentations"
	meta "payslips/pkg/meta"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPayslipSummary is a mock of PayslipSummary interface.
type MockPayslipSummary struct {
	ctrl     *gomock.Controller
	recorder *MockPayslipSummaryMockRecorder
}

// MockPayslipSummaryMockRecorder is the mock recorder for MockPayslipSummary.
type MockPayslipSummaryMockRecorder struct {
	mock *MockPayslipSummary
}

// NewMockPayslipSummary creates a new mock instance.
func NewMockPayslipSummary(ctrl *gomock.Controller) *MockPayslipSummary {
	mock := &MockPayslipSummary{ctrl: ctrl}
	mock.recorder = &MockPayslipSummaryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayslipSummary) EXPECT() *MockPayslipSummaryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPayslipSummary) Create(ctx context.Context, input presentations.PayslipSummary) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPayslipSummaryMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPayslipSummary)(nil).Create), ctx, input)
}

// List mocks base method.
func (m_2 *MockPayslipSummary) List(ctx context.Context, m *meta.Params, payrollID string) ([]presentations.PayslipSummary, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "List", ctx, m, payrollID)
	ret0, _ := ret[0].([]presentations.PayslipSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPayslipSummaryMockRecorder) List(ctx, m, payrollID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPayslipSummary)(nil).List), ctx, m, payrollID)
}
