// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/audit_log/contract.go

// Package auditlog is a generated GoMock package.
package auditlog

import (
	context "context"
	presentations "payslips/internal/presentations"
	meta "payslips/pkg/meta"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuditLog is a mock of AuditLog interface.
type MockAuditLog struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogMockRecorder
}

// MockAuditLogMockRecorder is the mock recorder for MockAuditLog.
type MockAuditLogMockRecorder struct {
	mock *MockAuditLog
}

// NewMockAuditLog creates a new mock instance.
func NewMockAuditLog(ctrl *gomock.Controller) *MockAuditLog {
	mock := &MockAuditLog{ctrl: ctrl}
	mock.recorder = &MockAuditLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLog) EXPECT() *MockAuditLogMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditLog) Create(ctx context.Context, input presentations.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLog)(nil).Create), ctx, input)
}

// List mocks base method.
func (m_2 *MockAuditLog) List(ctx context.Context, m *meta.Params) ([]presentations.AuditLog, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "List", ctx, m)
	ret0, _ := ret[0].([]presentations.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAuditLogMockRecorder) List(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditLog)(nil).List), ctx, m)
}
